l_english:
 MESSAGE_SETTINGS_WINDOW_NAME: ""
 MESSAGE_SETTINGS_WINDOW_TT: ""
 MESSAGE_SETTINGS_WINDOW_RESET: ""
 MESSAGE_SETTINGS_WINDOW_RESET_TT: ""
 MESSAGE_SETTINGS_WINDOW_APPLY: ""
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: ""
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: ""
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: ""
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: ""
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: ""
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: ""
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: ""
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: ""
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: ""
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: ""
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: ""
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: ""
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: ""
