:: BUILDER SETTINGS
set charset=empty
set project_folder="pliki"
set parser="tools\\LocaleParser\\bin\\LocaleParser-0.1.11-SNAPSHOT.jar"

set fty=folder_to_yaml
set gle=\\game\\localization\\english
set jom=\\jomini\\localization
set evtloc=\\event_localization

cd "%project_folder%"
echo "Usunięcie starych plików."
del /s /f /q en
mkdir en
cd ../
echo "Przekonwertowanie plików z ck3 na standardowe pliki yml."
::game
::główny
java -jar "%parser%" "%fty%" "orginal%gle%" "pliki\\en%gle%" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\accolades" "pliki\\en%gle%\\accolades" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\activities" "pliki\\en%gle%\\activities" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\artifacts" "pliki\\en%gle%\\artifacts" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\bookmark" "pliki\\en%gle%\\bookmark" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\credits" "pliki\\en%gle%\\credits" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\culture" "pliki\\en%gle%\\culture" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\culture\\traditions" "pliki\\en%gle%\\culture\\traditions" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\custom_localization" "pliki\\en%gle%\\custom_localization" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\diarchies" "pliki\\en%gle%\\diarchies" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\bp1" "pliki\\en%gle%\\dlc\\bp1" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\bp2" "pliki\\en%gle%\\dlc\\bp2" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ce1" "pliki\\en%gle%\\dlc\\ce1" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep1" "pliki\\en%gle%\\dlc\\ep1" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2" "pliki\\en%gle%\\dlc\\ep2" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2\\dynasty_legacies" "pliki\\en%gle%\\dlc\\ep2\\dynasty_legacies" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2\\pulse actions" "pliki\\en%gle%\\dlc\\ep2\\pulse actions" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2\\tour" "pliki\\en%gle%\\dlc\\ep2\\tour" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2\\tournament" "pliki\\en%gle%\\dlc\\ep2\\tournament" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2\\travel" "pliki\\en%gle%\\dlc\\ep2\\travel" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\ep2\\wedding" "pliki\\en%gle%\\dlc\\ep2\\wedding" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\fp1" "pliki\\en%gle%\\dlc\\fp1" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\fp2" "pliki\\en%gle%\\dlc\\fp2" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dlc\\fp3" "pliki\\en%gle%\\dlc\\fp3" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dynasties" "pliki\\en%gle%\\dynasties" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\dynasty_legacies" "pliki\\en%gle%\\dynasty_legacies" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\effects" "pliki\\en%gle%\\effects" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\enum" "pliki\\en%gle%\\enum" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%" "pliki\\en%gle%%evtloc%" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\activities" "pliki\\en%gle%%evtloc%\\activities" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\childhood" "pliki\\en%gle%%evtloc%\\childhood" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\councillor_task_events" "pliki\\en%gle%%evtloc%\\councillor_task_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\councillor_task_events\\councillor_spouse_events" "pliki\\en%gle%%evtloc%\\councillor_task_events\\councillor_spouse_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\court_events" "pliki\\en%gle%%evtloc%\\court_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\culture_events" "pliki\\en%gle%%evtloc%\\culture_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\death_events" "pliki\\en%gle%%evtloc%\\death_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\decisions" "pliki\\en%gle%%evtloc%\\decisions" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\experimental" "pliki\\en%gle%%evtloc%\\experimental" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\government_events" "pliki\\en%gle%%evtloc%\\government_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\hold_court_events" "pliki\\en%gle%%evtloc%\\hold_court_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle" "pliki\\en%gle%%evtloc%\\lifestyle" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle\\governance" "pliki\\en%gle%%evtloc%\\lifestyle\\governance" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle\\guile" "pliki\\en%gle%%evtloc%\\lifestyle\\guile" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle\\nickname" "pliki\\en%gle%%evtloc%\\lifestyle\\nickname" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle\\scholarship" "pliki\\en%gle%%evtloc%\\lifestyle\\scholarship" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle\\statecraft" "pliki\\en%gle%%evtloc%\\lifestyle\\statecraft" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\lifestyle\\warfare" "pliki\\en%gle%%evtloc%\\lifestyle\\warfare" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\prison_events" "pliki\\en%gle%%evtloc%\\prison_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\relation_events" "pliki\\en%gle%%evtloc%\\relation_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\religion_events" "pliki\\en%gle%%evtloc%\\religion_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes" "pliki\\en%gle%%evtloc%\\schemes" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\abduct" "pliki\\en%gle%%evtloc%\\schemes\\abduct" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\befriend" "pliki\\en%gle%%evtloc%\\schemes\\befriend" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\claim_throne" "pliki\\en%gle%%evtloc%\\schemes\\claim_throne" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\court" "pliki\\en%gle%%evtloc%\\schemes\\court" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\fabricate_hook" "pliki\\en%gle%%evtloc%\\schemes\\fabricate_hook" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\learn_language" "pliki\\en%gle%%evtloc%\\schemes\\learn_language" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\murder" "pliki\\en%gle%%evtloc%\\schemes\\murder" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\seduce" "pliki\\en%gle%%evtloc%\\schemes\\seduce" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\steal_back_artifact" "pliki\\en%gle%%evtloc%\\schemes\\steal_back_artifact" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\schemes\\sway" "pliki\\en%gle%%evtloc%\\schemes\\sway" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\secret_events" "pliki\\en%gle%%evtloc%\\secret_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\story_cycles" "pliki\\en%gle%%evtloc%\\story_cycles" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\stress_events" "pliki\\en%gle%%evtloc%\\stress_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\trait_specific_events" "pliki\\en%gle%%evtloc%\\trait_specific_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\travel_events" "pliki\\en%gle%%evtloc%\\travel_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\yearly_events" "pliki\\en%gle%%evtloc%\\yearly_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%%evtloc%\\war_event" "pliki\\en%gle%%evtloc%\\war_event" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\gui" "pliki\\en%gle%\\gui" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\hold_court_events" "pliki\\en%gle%\\hold_court_events" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\hostages" "pliki\\en%gle%\\hostages" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\interactions" "pliki\\en%gle%\\interactions" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\inventory" "pliki\\en%gle%\\inventory" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\lifestyles" "pliki\\en%gle%\\lifestyles" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\load_tips" "pliki\\en%gle%\\load_tips" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\map" "pliki\\en%gle%\\map" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\modifiers" "pliki\\en%gle%\\modifiers" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\names" "pliki\\en%gle%\\names" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\opinions" "pliki\\en%gle%\\opinions" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\portraits" "pliki\\en%gle%\\portraits" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\religion" "pliki\\en%gle%\\religion" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\travel" "pliki\\en%gle%\\travel" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\triggers" "pliki\\en%gle%\\triggers" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\tutorial" "pliki\\en%gle%\\tutorial" "%charset%"
java -jar "%parser%" "%fty%" "orginal%gle%\\struggles" "pliki\\en%gle%\\struggles" "%charset%"
::event_localization
::jomini
java -jar "%parser%" "%fty%" "orginal%jom%" "pliki\\en%jom%" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\achievements" "pliki\\en%jom%\\achievements" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\credits" "pliki\\en%jom%\\credits" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\frontend" "pliki\\en%jom%\\frontend" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\jomini" "pliki\\en%jom%\\jomini" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\jomini\\coat_of_arms" "pliki\\en%jom%\\jomini\\coat_of_arms" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\jomini\\multiplayer_gui" "pliki\\en%jom%\\jomini\\multiplayer_gui" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\jomini\\script_system" "pliki\\en%jom%\\jomini\\script_system" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\pops" "pliki\\en%jom%\\pops" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\settings" "pliki\\en%jom%\\settings" "%charset%"
java -jar "%parser%" "%fty%" "orginal%jom%\\social" "pliki\\en%jom%\\social" "%charset%"

::clausewitz
java -jar "%parser%" "%fty%" "orginal\\clausewitz\\localization" "pliki\\en\\clausewitz\\localization" "%charset%"
java -jar "%parser%" "%fty%" "orginal\\clausewitz\\localization\\text_utils" "pliki\\en\\clausewitz\\localization\\text_utils" "%charset%"





echo "Koniec."
pause